# Imagen base
FROM node:22.15

# Crear carpeta de trabajo
WORKDIR /app

# Copiar backend y frontend
COPY backend/ backend/
COPY frontend/ frontend/

# Instalar dependencias
WORKDIR /app/backend
COPY backend/package*.json ./
RUN npm install

# Exponer puerto de la API
EXPOSE 5000

# Comando para arrancar el backend
CMD ["npm", "start"]