name: Node Build
run-name: Build  nodejs app
on: [push]
jobs:
  Build:
    runs-on: [self-hosted]
    steps:
      - name: Descargar el repositorio
        uses: actions/checkout@v4
      - name: Configurar Nodejs
        uses: actions/setup-node@v4
        with:
            node-version: '22.x'
      - name: Instalar dependencias
        working-directory: ./calculadora
        run: |
            npm install
      - name: Instalar dependencias
        working-directory: ./calculadora
        run: |
            npm run build
